<?php

use \Illuminate\Auth\Notifications\ResetPassword as ResetPasswordBase;

class ResetPassword extends ResetPasswordBase
{
    public function toMail($notifiable)
    {
        return parent::toMail($notifiable)->to; // TODO: Change the autogenerated stub
    }
}
